name: lux
description: A Guilded wrapper written in Dart.
homepage: https://github.com/benfrste/lux
repository: https://github.com/benfrstr/lux
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  http: ^1.2.1
  web_socket_channel: ^2.4.4
  
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
